---
version: '3.2'
volumes:
  zookeeper-logs:
  zookeeper-data:
  kafka-logs:
  kafka-data:
services:
  zookeeper:
    image: zookeeper-single
    network_mode: host
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - type: volume
        source: zookeeper-logs
        target: /var/log/zookeeper
        volume:
          nocopy: true
      - zookeeper-data:/var/opt/zookeeper
  kafka:
    image: kafka-single
    network_mode: host
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: localhost:181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka-logs:/var/log/kafka
      - kafka-data:/var/opt/kafka

